language: cpp

matrix:
  include:
    - os: windows
      name: "windows"
      env:
        - MSBUILD_PATH="/C/Program Files (x86)/MSBuild/14.0/Bin:/C/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin"
      script:
        - choco install vcbuildtools -ia "/InstallSelectableItems Win81SDK_CppBuildSKUV1;VisualCppBuildTools_ATLMFC_SDK"
        - export PATH=$MSBUILD_PATH:$PATH
        - cd oactobjs32
        - wget -q "https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.zip"
        - 7z x -bd boost_1_64_0.zip
        - cd boost_1_64_0
        - ./bootstrap.bat
        - ./b2.exe toolset=msvc-14.0 link=static runtime-link=static threading=multi --with-date_time
        - cd ..
        - cd ..
        - cd anypiab
        - MSBuild.exe
        - cd ..
        - cd anypia32
        - MSBuild.exe
    - name: "linux-anypiab"
      os: linux
      dist: bionic
      addons:
        apt:
          packages: libboost-date-time-dev
      script:
        - mkdir anypiab/build
        - cd anypiab/build
        - cmake ..
        - make
    - name: "mac-anypiab"
      os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          packages:
            - cmake
            - boost
      script:
        - mkdir anypiab/build
        - cd anypiab/build
        - cmake ..
        - make
    - name: "emscripten-anypiab-mac"
      os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          packages:
            - cmake
            - boost
            - emscripten
      script:
        # Needed to use Homebrew's emscripten
        - export LLVM=/usr/local/opt/emscripten/libexec/llvm/bin
        - export BINARYEN=/usr/local/opt/binaryen
        - wget -q "https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.zip"
        - unzip -q boost_1_64_0.zip
        - cd boost_1_64_0
        - ./bootstrap.sh
        - ./b2 toolset=emscripten link=static runtime-link=static --with-date_time
        - export BOOST_INCL=`pwd`
        - export BOOST_LIB=`pwd`/stage/lib
        - cd ..
        - mkdir anypiab/build
        - cd anypiab/build
        - emcmake cmake -DBOOST_INCLUDEDIR=$BOOST_INCL -DBOOST_LIBRARYDIR=$BOOST_LIB ..
        - make -j2
    - os: windows
      name: "emscripten-anypiab-windows"
      python: "3.8"
      before_install:
        - choco install python3 --version=3.8
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      env:
        - MSBUILD_PATH="/C/Program Files (x86)/MSBuild/14.0/Bin:/C/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin"
      script:
        - python --version
        - echo "available python version must be greater than 2.7.13 or pip install certifi"
        - git clone https://github.com/emscripten-core/emsdk.git
        - cd emsdk
        - ./emsdk.bat install latest
        - ./emsdk.bat activate latest
        - cd .. 
        - choco install vcbuildtools -ia "/InstallSelectableItems Win81SDK_CppBuildSKUV1;VisualCppBuildTools_ATLMFC_SDK"
        - export PATH=$MSBUILD_PATH:$PATH
        - cd oactobjs32
        - wget -q "https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.zip"
        - 7z x -bd boost_1_64_0.zip
        - cd boost_1_64_0
        - ./bootstrap.bat
        - ./b2.exe toolset=msvc-14.0 link=static address-model=32 architecture=x86 runtime-link=static threading=multi --layout=versioned --with-date_time
        - export BOOST_INCL="`pwd`"
        - export BOOST_LIB="`pwd`\stage\lib"
        - cd ../..
        - cd anypiab
        - mkdir build
        - cd build
        - ../../emsdk/upstream/emscripten/emcmake cmake -DBOOST_ROOT=$BOOST_INCL -DBOOST_LIBRARYDIR=$BOOST_LIB -G "NMake Makefiles" ..
        - nmake